### ISSUE TITLE
protoc-gen-grpchan should append "Server" to Register function

### ISSUE THREAD

**Issue by RangelReale** [fullstorydev/grpchan#14]
First great work on this library, it is awesome!

protoc-gen-grpchan generates the server registration without "Server" at the end of the function name, like the protoc-gen-go does, I think it may be better to keep this consistency.

**Comment by jhump** [comment]
This was intentional to keep the generated function names from being overly long. The thinking was that `Handler` in the generated names is sufficient to indicate that this is for server-side.
