### ISSUE TITLE
Gogo support?

### ISSUE THREAD

**Issue by maros7** [fullstorydev/grpchan#19]
Hi, would you consider adding official support for https://github.com/gogo/protobuf? Using inprocgrpc causes panic when `.proto`s are compiled with gogo/protobuf and not golang/protobuf. I can of course create my own version of inprocgrpc, but would be good I guess to have it in this repository. I can look into submitting a PR.

**Comment by jhump** [comment]
I do not want to add any dependency from packages in this repo to gogo/protobuf -- that is just dependency baggage/bloat for people that use golang/protobuf.

One option would be to make the message cloning pluggable. That way your code could provide a custom cloner that used gogo/protobuf without adding it as a dependency to inprocgrpc itself. I'll look into that.

Also note that this will likely be addressed in the future: one of the objectives of the [v2 API of the protobuf runtime](https://docs.google.com/document/d/19kfhro7-CnBdFqFk7l4_HmwaH2JT_Rhw5-2FLWLEGGk/edit#heading=h.q3iwtwhfujjx) is to support other kinds of proto messages -- such as those generated by gogo's protoc plugin, or even [dynamic messages](https://godoc.org/github.com/jhump/protoreflect/dynamic).

**Comment by maros7** [comment]
Fair enough. And thanks for the detailed answer. I’ll just create a custom channel for now.

**Comment by maros7** [comment]
Thanks. I will try this and get back to you.

**Comment by maros7** [comment]
Hey. Yes, this solves my issue. Thanks!

**Comment by jhump** [comment]
@maros7, I just merged that branch. But be aware that I made some non-trivial changes to the `Cloner` interface. I revised the example above so that it should work -- just make sure you grab the latest changes to that gogo example. (Most urgently, I swapped the order of args to the `Copy` method, so its signature is now consistent with the `copy` builtin.)
